"""initial

Revision ID: ef70ca68a7a1
Revises: 
Create Date: 2026-07-22 17:15:57.871319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef70ca68a7a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=14), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('observacoes', sa.String(length=1000), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('unidade_medida', sa.String(length=20), nullable=False),
    sa.Column('preco_custo', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('estoque_atual', sa.Integer(), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vendas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=True),
    sa.Column('cliente_nome', sa.String(length=200), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_nome', sa.String(length=200), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendas_cliente_id'), 'vendas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_vendas_data_hora'), 'vendas', ['data_hora'], unique=False)
    op.create_index(op.f('ix_vendas_usuario_id'), 'vendas', ['usuario_id'], unique=False)
    op.create_table('itens_venda',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('venda_id', sa.Uuid(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=False),
    sa.Column('produto_nome', sa.String(length=200), nullable=False),
    sa.Column('produto_sku', sa.String(length=50), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_venda_momento', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('preco_custo_momento', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_venda_produto_id'), 'itens_venda', ['produto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_venda_produto_id'), table_name='itens_venda')
    op.drop_table('itens_venda')
    op.drop_index(op.f('ix_vendas_usuario_id'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_data_hora'), table_name='vendas')
    op.drop_index(op.f('ix_vendas_cliente_id'), table_name='vendas')
    op.drop_table('vendas')
    op.drop_table('usuarios')
    op.drop_table('tenants')
    op.drop_table('produtos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
